export const resources = [
  {
    type: "test",
    event: "Write It Do It",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGWE1pVUxFZ0ZQX1k/view?usp=sharing&resourcekey=0-zv_ITKb9sFjPvktdT3U7tA",
    key: "https://drive.google.com/file/d/0By856O3q58sGVmRSMEVRUXlXbmM/view?usp=sharing&resourcekey=0-GPBs-Zzb7MGfhCtZOexpvQ",
  },
  {
    type: "test",
    event: "We've Got Your Number",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGV2JxVkxvQUE1VUk/view?usp=sharing&resourcekey=0-Hne6LxmZnb37wrLnXJfv6Q",
  },
  {
    type: "test",
    event: "We've Got Your Number",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGN3dQeFozaERBLVE/view?usp=sharing&resourcekey=0-tFANeNgqFATDWYTk79XsWw",
  },
  {
    type: "test",
    event: "Water Quality",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGS3YxNHVmSVRDMEk/view?usp=sharing&resourcekey=0-EvVvW-eFEZUvbfSCiWhpPw",
    key: "https://drive.google.com/file/d/0By856O3q58sGTkpIT0djUU40NkU/view?usp=sharing&resourcekey=0-hmnOawYFXBtG_ws4NsK76A",
  },
  {
    type: "test",
    event: "Technical Problem Solving",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGMk9fR1JaX29yTnM/view?usp=sharing&resourcekey=0-f5HX78rCclsVc5uYaEyGtg",
    key: "https://drive.google.com/file/d/0By856O3q58sGYmIxV09SVFJTQ0U/view?usp=sharing&resourcekey=0-COGbq4vbmTlW9OFrR-yr1Q",
  },
  {
    type: "scoresheet",
    event: "Storm the Castle",
    year: "2011-2012",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGVGJZSlhVZFQ1Q28/view?usp=sharing&resourcekey=0-9Y0XfJ4ryWInyliv3SEkAw",
    key: "https://drive.google.com/file/d/0By856O3q58sGVF9yY2JCN3VVbEk/view?usp=sharing&resourcekey=0-pwYH_Tjf-KQ7Uzbrgc54og",
  },
  {
    type: "scoresheet",
    event: "Scrambler",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGVlUtbEpYcHpyYzQ/view?usp=sharing&resourcekey=0-FY0Ybs947-40ONo_1TEZ7A",
  },
  {
    type: "test",
    event: "Science Word",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGREhpSVV5NDdTLVk/view?usp=sharing&resourcekey=0-3Mia_WlNY28mqVuPlDUzyQ",
    key: "https://drive.google.com/file/d/0By856O3q58sGTUVla2ZxQ1F3ZWs/view?usp=sharing&resourcekey=0-lmJsR4ao6DOo5O6I9OWuRw",
  },
  {
    type: "test",
    event: "Rocks and Minerals",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGYmVORXVhY1kzeVk/view?usp=sharing&resourcekey=0-kiHH96VCpvnyrC1cq5b8vQ",
    key: "https://drive.google.com/file/d/0By856O3q58sGbVNiUG11SUJOOWc/view?usp=sharing&resourcekey=0-Z_vXS8ESH_xo4qhbQxYa4w",
    notes: "missing lab",
  },
  {
    type: "scoresheet",
    event: "Mission Possible",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGaV9OWUJ4SC01RHM/view?usp=sharing&resourcekey=0-Gk7UAiUnXY4hIf5GJtTfSA",
  },
  {
    type: "test",
    event: "Mission Possible",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGZm5qLWRlNXBIdnM/view?usp=sharing&resourcekey=0-LXOVk6mYilzN1ClVpoMKPA",
  },
  {
    type: "test",
    event: "Material Science",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGbDV6TnNyMjRTYXM/view?usp=sharing&resourcekey=0-Ut86lvvU_sgmNMshO_64cg",
    key: "https://drive.google.com/file/d/0By856O3q58sGZTF4cmdJLUJ5NU0/view?usp=sharing&resourcekey=0-rX2kZT2Qi25b3aavGKF-FA",
    notes: "missing lab",
  },
  {
    type: "scoresheet",
    event: "Mag Lev",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGOTl2SjBBaHNmcjA/view?usp=sharing&resourcekey=0-rz_plMG6x2sdq6xY2GjprQ",
  },
  {
    type: "test",
    event: "Mag Lev",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGczVvcXFzMUF5dXc/view?usp=sharing&resourcekey=0-yIYIjzGto39Kqq5budAl-A",
    key: "https://drive.google.com/file/d/0By856O3q58sGRmNFVUExSlMzQW8/view?usp=sharing&resourcekey=0-lKOHA2PaZKO8xhBykN7CMQ",
  },
  {
    type: "test",
    event: "Geologic Mapping",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGVWZxZUljbm9PN1U/view?usp=sharing&resourcekey=0-OPINZBBfiLnnUGmsexk9iw",
    key: "https://drive.google.com/file/d/0By856O3q58sGd1FINmdFeTBjcHM/view?usp=sharing&resourcekey=0-uRwPN589IoEfeGd6Evlpmg",
    "answer sheet":
      "https://drive.google.com/file/d/0By856O3q58sGVzlIb2ZYRzN2OG8/view?usp=sharing&resourcekey=0-wk1Krjtbq6S0evi8GUeAAg",
  },
  {
    type: "test",
    event: "Fossils",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGcHdYT3A5TjNNUFE/view?usp=sharing&resourcekey=0-yp0qnHdp8zfrRvOvzvXOMQ",
    key: "https://drive.google.com/file/d/0By856O3q58sGckV0XzJuUEtvNHc/view?usp=sharing&resourcekey=0-AX7n6afDUKWfp2UU-UmshQ",
    notes: "missing images",
  },
  {
    type: "test",
    event: "Forensics",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGWGEtS1BJS1Z2V2M/view?usp=sharing&resourcekey=0-XZH0Wxah9TE_j15SbvEaMA",
    key: "https://drive.google.com/file/d/0By856O3q58sGc0ZUbE5aYlFnZGM/view?usp=sharing&resourcekey=0-PGp0mHctkG55pwA-Gg3XYA",
  },
  {
    type: "test",
    event: "Fermi Questions",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGVUFGZHVxX3ZoRkU/view?usp=sharing&resourcekey=0-Qp80ba5wC21D78nPbjaDgg",
    key: "https://drive.google.com/file/d/0By856O3q58sGaHpINjFMX3VJNTA/view?usp=sharing&resourcekey=0-6yQD8ZOV2SgiIOJt8bMkhw",
    "answer sheet":
      "https://drive.google.com/file/d/0By856O3q58sGWDBPNlk4ck5NcUE/view?usp=sharing&resourcekey=0-MbDkfARs6vXyD_9DKZpmiw",
  },
  {
    type: "test",
    event: "Experimental Design",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGTldJQjRibWh3TWc/view?usp=sharing&resourcekey=0-iki_hf0zdtvNWxbTmsvkwg",
    key: "https://drive.google.com/file/d/0By856O3q58sGQ2VsbGExX1Z4dEE/view?usp=sharing&resourcekey=0-H67FGUD8VYMxIDmcOcLLfA",
  },
  {
    type: "test",
    event: "Entomology",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGellNVDg5WkJuWXM/view?usp=sharing&resourcekey=0-gH4VoWxvHxX55c_3NeIL6w",
    key: "https://drive.google.com/file/d/0By856O3q58sGSmtHVm9yYVQtRnM/view?usp=sharing&resourcekey=0-5jiH9292WlpKR7vR_gFfYg",
    notes: "missing images",
  },
  {
    type: "scoresheet",
    event: "Elastic Launch Glider",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGRjlKSVltOHhzZ1k/view?usp=sharing&resourcekey=0-PxW3UuN5-YQcguSHw8O4Zg",
  },
  {
    type: "test",
    event: "Dynamic Planet",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGWl96cUFFMzBDRFk/view?usp=sharing&resourcekey=0-Dda8kvD0hWt36-8UABEN_g",
    key: "https://drive.google.com/file/d/0By856O3q58sGdFM5V3lSMi11SUE/view?usp=sharing&resourcekey=0-LjxIFVyrMtkySNgONQtMtw",
  },
  {
    type: "test",
    event: "Disease Detectives",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGRGdpcXNpZjZvb0k/view?usp=sharing&resourcekey=0-FQI3D2jb-bQbeY4ATl2scQ",
    key: "https://drive.google.com/file/d/0By856O3q58sGeVI4M09uZjRoWDg/view?usp=sharing&resourcekey=0-MwjUlDyRwJUbHRPUwTEn1g",
    notes: "this is a corrected version",
  },
  {
    type: "test",
    event: "Designer Genes",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGVG9Bd3VtVWptbTQ/view?usp=sharing&resourcekey=0-fampr7j8Ri8KqDfZl6oJ9g",
    key: "https://drive.google.com/file/d/0By856O3q58sGa2lPYnIxZ2hBbDg/view?usp=sharing&resourcekey=0-JQcebn3zFLQPGhTTKN0g2Q",
    "answer sheet":
      "https://drive.google.com/file/d/0By856O3q58sGM1NLVEZIZTNxajQ/view?usp=sharing&resourcekey=0-_u7pW1Z7zivGxx50GW9MDg",
  },
  {
    type: "test",
    event: "Compound Machines",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGU2dKbHhjeU9abTg/view?usp=sharing&resourcekey=0-N7Zo1yEX6YgFh57rjuTjig",
    key: "https://drive.google.com/file/d/0By856O3q58sGOXF1OVlESDNtX2M/view?usp=sharing&resourcekey=0-MJ3Rf19Oq9KJ4W3VaDC3MA",
  },
  {
    type: "scoresheet",
    event: "Compound Machines",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGZjZ2NGtUSFM0WEk/view?usp=sharing&resourcekey=0-gf61x1QXS_6WsHGRw63aCg",
  },
  {
    type: "test",
    event: "Circuit Lab",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGUzE3akg4dm5LNzA/view?usp=sharing&resourcekey=0-fShuB9ACVdohMGv-2kMCqg",
    key: "https://drive.google.com/file/d/0By856O3q58sGcGhGdTNSbXVoNDg/view?usp=sharing&resourcekey=0-2YUTXOSze3CP3dZ9KFLzCg",
  },
  {
    type: "test",
    event: "Chemistry Lab",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGbkRGZVk5N0RibXc/view?usp=sharing&resourcekey=0-F_wUjfrGIweL3fw6psWM9Q",
    key: "https://drive.google.com/file/d/0By856O3q58sGYkVzc3E1eFJUVFU/view?usp=sharing&resourcekey=0-CSKcaXY2wqFZTXoIkfpQbQ",
    notes: "missing lab",
  },
  {
    type: "scoresheet",
    event: "Bungee Drop",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGeW1kTmdVU2hvYUk/view?usp=sharing&resourcekey=0--tC3iZ3lpFQpt5REoLnD5w",
  },
  {
    type: "scoresheet",
    event: "Boomilever",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGMHRtZnFTamVnZTg/view?usp=sharing&resourcekey=0-T9PEltPrW9lquf2GCdrtpg",
  },
  {
    type: "test",
    event: "Astronomy",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGdnRwRm9XVEdTUTQ/view?usp=sharing&resourcekey=0-DVwz2PA-dy0L5k4chChtjQ",
    key: "https://drive.google.com/file/d/0By856O3q58sGMjcxZE1EVW5GNGc/view?usp=sharing&resourcekey=0-askvYjasTdi0Mxpy8waWsg",
  },
  {
    type: "test",
    event: "Anatomy and Physiology",
    year: "2013-2014",
    tournament: "UT Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGa3psZThmNVVDQW8/view?usp=sharing&resourcekey=0-SEfpSmGVg_x6lyVLnBoLGQ",
    key: "https://drive.google.com/file/d/0By856O3q58sGV0puZll5dHpQSDQ/view?usp=sharing&resourcekey=0-n_JXFCwHRZMfZDXrdozMMQ",
    notes: "Also the New York State Science Olympiad Regional of 2014",
  },
  {
    type: "test",
    event: "Write It Do It",
    year: "2014-2015",
    tournament: "Yale Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGYlNOMnBGVm14STg/view?usp=sharing&resourcekey=0-DiS1dDLGjvMJF1MVeauq-Q",
    links: [
      "https://drive.google.com/file/d/0By856O3q58sGVTNFSEc0aUt4WEU/view?usp=sharing&resourcekey=0-Ri2DjZSqyMSH0Tp52C5hUA",
      "https://drive.google.com/file/d/0By856O3q58sGV0w2eXFSV2ZPc1E/view?usp=sharing&resourcekey=0-WzOLMYSUvuNUmReJxvwSQQ",
      "https://drive.google.com/file/d/0By856O3q58sGNnhnNE0tS3BIclE/view?usp=sharing&resourcekey=0-7sg3rYih4w2VzOzmhVrxVw",
      "https://drive.google.com/file/d/0By856O3q58sGY1NIQ1JMbWNjcjQ/view?usp=sharing&resourcekey=0-utcRc0mzpRfzqNkLgAAznQ",
      "https://drive.google.com/file/d/0By856O3q58sGUmM2Nlh2NXFMd1E/view?usp=sharing&resourcekey=0-_kgigDzRjpEMKTHD5X_0XA",
      "https://drive.google.com/file/d/0By856O3q58sGaWd1d2d2SVQ3VlU/view?usp=sharing&resourcekey=0-FyFYSm_hal1M2dra3WNQKg",
    ],
    key: "https://drive.google.com/file/d/0By856O3q58sGOEpLQnZzOFpWRms/view?usp=sharing&resourcekey=0-_vIEZBiVScBOoisWayDUMQ",
    notes: "structure images in additional links",
  },
  {
    type: "test",
    event: "Technical Problem Solving",
    year: "2014-2015",
    tournament: "Yale Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGcUhLSDZtbmw4NDQ/view?usp=sharing&resourcekey=0-k-zKF_diODKAayIk3X9Ijw",
    key: "https://drive.google.com/file/d/0By856O3q58sGbUZnbjJEMktHMFU/view?usp=sharing&resourcekey=0-TxOby2iRhg39dZt6J3rfIw",
    notes: "missing lab",
    "answer sheet":
      "https://drive.google.com/file/d/0By856O3q58sGWE1EQkJtcFpiTEk/view?usp=sharing&resourcekey=0-ChbiMsHmvp-yijcPWb5u_A",
  },
  {
    type: "test",
    event: "Protein Modeling",
    year: "2014-2015",
    tournament: "Yale Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGZnRJRWpmWU5Ybms/view?usp=sharing&resourcekey=0-0zmmWgZXe1SiG48qPaiMxA",
    links: [
      "https://drive.google.com/file/d/0By856O3q58sGbkhwZXczaWZ0Yjg/view?usp=sharing&resourcekey=0-SXhZBtT9YfbGAiAmckmyDg",
    ],
    key: "https://drive.google.com/file/d/0By856O3q58sGeUJ0Yy1tT29BQVU/view?usp=sharing&resourcekey=0-vBEvFZvbL_wBmYza46ab9Q",
    notes: "Lab portion link below",
  },
  {
    type: "scoresheet",
    event: "Protein Modeling",
    year: "2014-2015",
    tournament: "Yale Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGMEdPVHMyY2dONjQ/view?usp=sharing&resourcekey=0-4ZP7tba6Dbb8WbyDp0bKsA",
  },
  {
    type: "test",
    event: "It's About Time",
    year: "2014-2015",
    tournament: "Yale Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGSm5CcVZmbkVhWWM/view?usp=sharing&resourcekey=0-XTz3RlZ9WdYJiTVebAcsIg",
    key: "https://drive.google.com/file/d/0By856O3q58sGQWJrbXBHMkJITHM/view?usp=sharing&resourcekey=0-xaKEkrblWiPmBiKllMfAHA",
  },
  {
    type: "test",
    event: "Green Generation",
    year: "2014-2015",
    tournament: "Yale Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGMVFFcEcwNFlSSVE/view?usp=sharing&resourcekey=0-pnKo0MXUxKejyYahQc4KnA",
    key: "https://drive.google.com/file/d/0By856O3q58sGUkNiRFRFVmk5eUk/view?usp=sharing&resourcekey=0-RuSHxpA52105jzZ3GIDtgQ",
  },
  {
    type: "test",
    event: "Geologic Mapping",
    year: "2014-2015",
    tournament: "Yale Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGVldka2xncG9GNmM/view?usp=sharing&resourcekey=0-ukLuQmgdBtazHVaQdPESTw",
    links: [
      "https://drive.google.com/file/d/0By856O3q58sGaGRfXzNrUFpJWFU/view?usp=sharing&resourcekey=0-79Nafs6FUXTBlZyBO3Y6DA",
      "https://drive.google.com/file/d/0By856O3q58sGRU1QSTJwWHpTZDg/view?usp=sharing&resourcekey=0-pmBPOieSNkO3cbk4ZZuPmg",
    ],
    key: "https://drive.google.com/file/d/0By856O3q58sGamZ2Q2d2aWowTmc/view?usp=sharing&resourcekey=0-tKEwHUQHa_Gjtd7xGESmDQ",
    notes: "images and Stereonet in additional links",
  },
  {
    type: "test",
    event: "Fossils",
    year: "2014-2015",
    tournament: "Yale Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGNGFwYS14YXJVWmM/view?usp=sharing&resourcekey=0-Qt1z5FXgNSZ9RZZ5vaISbQ",
    links: [
      "https://drive.google.com/file/d/0By856O3q58sGbmtMc2l5NGpUOFE/view?usp=sharing&resourcekey=0-qJh9Vvqc5tX88LS-3nVSYA",
    ],
    key: "https://drive.google.com/file/d/0By856O3q58sGOFBKOGVITXVCakE/view?usp=sharing&resourcekey=0-SJu3xP3bdgnDc0n7ivK-2A",
    notes: "missing stations; stations key in additional links",
  },
  {
    type: "test",
    event: "Experimental Design",
    year: "2014-2015",
    tournament: "Yale Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGek00VFlzNmdLeWs/view?usp=sharing&resourcekey=0-1nxmv4QKG-9UcboNiHe_sw",
    key: "https://drive.google.com/file/d/0By856O3q58sGRWduUWNHamgxYW8/view?usp=sharing&resourcekey=0-Pn9xEmioeq-XZQr4SmgM2w",
  },
  {
    type: "test",
    event: "Entomology",
    year: "2014-2015",
    tournament: "Yale Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGSURDRHJIUUhoVmc/view?usp=sharing&resourcekey=0-r3swz17Bg4QFztHp1eoFgA",
    key: "https://drive.google.com/file/d/0By856O3q58sGNE0tbVgzT3dMaXM/view?usp=sharing&resourcekey=0-8Xjm1sq6dzkeOhUDFeGwWQ",
  },
  {
    type: "test",
    event: "Dynamic Planet",
    year: "2014-2015",
    tournament: "Yale Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGSHNqaHJpWlJmakk/view?usp=sharing&resourcekey=0-zVr5FHIKBglJIST-CbaW6g",
    key: "https://drive.google.com/file/d/0By856O3q58sGUXFFcjJYc0x0eHc/view?usp=sharing&resourcekey=0-41uHpF7bTeymo-a2_QldpA",
  },
  {
    type: "test",
    event: "Disease Detectives",
    year: "2014-2015",
    tournament: "Yale Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGZFEzd1dIa29iZWs/view?usp=sharing&resourcekey=0-uksTHOckGNytBCGHNQnmrA",
    key: "https://drive.google.com/file/d/0By856O3q58sGYzUyNkNZemZ3YWs/view?usp=sharing&resourcekey=0-wNuUUQFKUAlmsogIrJ_0Gw",
  },
  {
    type: "test",
    event: "Compound Machines",
    year: "2014-2015",
    tournament: "Yale Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGZk9ac1ctLTYxUlE/view?usp=sharing&resourcekey=0-k3W07kEwjz9G8iXp1nG-DA",
    key: "https://drive.google.com/file/d/0By856O3q58sGSEFMRzJUNHZhN1U/view?usp=sharing&resourcekey=0-uBR6f5c3nBVyB-TbS5L9iQ",
  },
  {
    type: "test",
    event: "Chemistry Lab",
    year: "2014-2015",
    tournament: "Yale Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGaEE2bXIwODB3T0E/view?usp=sharing&resourcekey=0-CDtn4LCT9dGHL4ronwLJaw",
    key: "https://drive.google.com/file/d/0By856O3q58sGYTd3LW91QmlqbG8/view?usp=sharing&resourcekey=0-zhrGlWpJafmu-iUe6uD-rw",
  },
  {
    type: "test",
    event: "Cell Biology",
    year: "2014-2015",
    tournament: "Yale Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGaE5qRVV1Y0Z1MEU/view?usp=sharing&resourcekey=0-Bhg76jFc_9IGQIpkwaSz_g",
    key: "https://drive.google.com/file/d/0By856O3q58sGT3ZtQnl3RHJnRmM/view?usp=sharing&resourcekey=0-R6xEWSpKPnrsv4b4baCXkQ",
  },
  {
    type: "test",
    event: "Astronomy",
    year: "2014-2015",
    tournament: "Yale Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGMk1PU2xQdkxZXzg/view?usp=sharing&resourcekey=0-UI93xF0Y_Oq0j2HzgKk_wg",
    links: [
      "https://drive.google.com/file/d/0By856O3q58sGbkNnSDdTQ2ppMEU/view?usp=sharing&resourcekey=0-ql0w5Zo_1NWcBs4dn5_P-w",
    ],
    key: "https://drive.google.com/file/d/0By856O3q58sGRXVHMHVwM1BRZE0/view?usp=sharing&resourcekey=0-T-ry7sa9FbLOqQvr7vZIOQ",
    notes: "images in additional links",
  },
  {
    type: "test",
    event: "Anatomy and Physiology",
    year: "2014-2015",
    tournament: "Yale Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGaWZHOEJqNGFHV2s/view?usp=sharing&resourcekey=0-pxorWeunCTevNAsEu5RCOg",
    key: "https://drive.google.com/file/d/0By856O3q58sGMm51YzBZY3RmYWs/view?usp=sharing&resourcekey=0-dq9VJngbAgBWaIquX6Xv2g",
  },
  //=====
  {
    type: "test",
    event: "Write It Do It",
    year: "2014-2015",
    tournament: "Westlake Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGYlNOMnBGVm14STg/view?usp=sharing&resourcekey=0-DiS1dDLGjvMJF1MVeauq-Q",
    links: [
      "https://drive.google.com/file/d/0By856O3q58sGVTNFSEc0aUt4WEU/view?usp=sharing&resourcekey=0-Ri2DjZSqyMSH0Tp52C5hUA",
      "https://drive.google.com/file/d/0By856O3q58sGV0w2eXFSV2ZPc1E/view?usp=sharing&resourcekey=0-WzOLMYSUvuNUmReJxvwSQQ",
      "https://drive.google.com/file/d/0By856O3q58sGNnhnNE0tS3BIclE/view?usp=sharing&resourcekey=0-7sg3rYih4w2VzOzmhVrxVw",
      "https://drive.google.com/file/d/0By856O3q58sGY1NIQ1JMbWNjcjQ/view?usp=sharing&resourcekey=0-utcRc0mzpRfzqNkLgAAznQ",
      "https://drive.google.com/file/d/0By856O3q58sGUmM2Nlh2NXFMd1E/view?usp=sharing&resourcekey=0-_kgigDzRjpEMKTHD5X_0XA",
      "https://drive.google.com/file/d/0By856O3q58sGaWd1d2d2SVQ3VlU/view?usp=sharing&resourcekey=0-FyFYSm_hal1M2dra3WNQKg",
    ],
    key: "https://drive.google.com/file/d/0By856O3q58sGOEpLQnZzOFpWRms/view?usp=sharing&resourcekey=0-_vIEZBiVScBOoisWayDUMQ",
    notes: "structure images in additional links",
  },
  {
    type: "test",
    event: "Technical Problem Solving",
    year: "2014-2015",
    tournament: "Westlake Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGcUhLSDZtbmw4NDQ/view?usp=sharing&resourcekey=0-k-zKF_diODKAayIk3X9Ijw",
    key: "https://drive.google.com/file/d/0By856O3q58sGbUZnbjJEMktHMFU/view?usp=sharing&resourcekey=0-TxOby2iRhg39dZt6J3rfIw",
    notes: "missing lab",
    "answer sheet":
      "https://drive.google.com/file/d/0By856O3q58sGWE1EQkJtcFpiTEk/view?usp=sharing&resourcekey=0-ChbiMsHmvp-yijcPWb5u_A",
  },
  {
    type: "test",
    event: "Protein Modeling",
    year: "2014-2015",
    tournament: "Westlake Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGZnRJRWpmWU5Ybms/view?usp=sharing&resourcekey=0-0zmmWgZXe1SiG48qPaiMxA",
    links: [
      "https://drive.google.com/file/d/0By856O3q58sGbkhwZXczaWZ0Yjg/view?usp=sharing&resourcekey=0-SXhZBtT9YfbGAiAmckmyDg",
    ],
    key: "https://drive.google.com/file/d/0By856O3q58sGeUJ0Yy1tT29BQVU/view?usp=sharing&resourcekey=0-vBEvFZvbL_wBmYza46ab9Q",
    notes: "Lab portion link below",
  },
  {
    type: "scoresheet",
    event: "Protein Modeling",
    year: "2014-2015",
    tournament: "Westlake Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGMEdPVHMyY2dONjQ/view?usp=sharing&resourcekey=0-4ZP7tba6Dbb8WbyDp0bKsA",
  },
  {
    type: "test",
    event: "It's About Time",
    year: "2014-2015",
    tournament: "Westlake Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGSm5CcVZmbkVhWWM/view?usp=sharing&resourcekey=0-XTz3RlZ9WdYJiTVebAcsIg",
    key: "https://drive.google.com/file/d/0By856O3q58sGQWJrbXBHMkJITHM/view?usp=sharing&resourcekey=0-xaKEkrblWiPmBiKllMfAHA",
  },
  {
    type: "test",
    event: "Green Generation",
    year: "2014-2015",
    tournament: "Westlake Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGMVFFcEcwNFlSSVE/view?usp=sharing&resourcekey=0-pnKo0MXUxKejyYahQc4KnA",
    key: "https://drive.google.com/file/d/0By856O3q58sGUkNiRFRFVmk5eUk/view?usp=sharing&resourcekey=0-RuSHxpA52105jzZ3GIDtgQ",
    notes: "structure images in additional links",
  },
  {
    type: "test",
    event: "Geologic Mapping",
    year: "2014-2015",
    tournament: "Westlake Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGVldka2xncG9GNmM/view?usp=sharing&resourcekey=0-ukLuQmgdBtazHVaQdPESTw",
    links: [
      "https://drive.google.com/file/d/0By856O3q58sGaGRfXzNrUFpJWFU/view?usp=sharing&resourcekey=0-79Nafs6FUXTBlZyBO3Y6DA",
      "https://drive.google.com/file/d/0By856O3q58sGRU1QSTJwWHpTZDg/view?usp=sharing&resourcekey=0-pmBPOieSNkO3cbk4ZZuPmg",
    ],
    key: "https://drive.google.com/file/d/0By856O3q58sGamZ2Q2d2aWowTmc/view?usp=sharing&resourcekey=0-tKEwHUQHa_Gjtd7xGESmDQ",
    notes: "images and Stereonet in additional links",
  },
  {
    type: "test",
    event: "Fossils",
    year: "2014-2015",
    tournament: "Westlake Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGNGFwYS14YXJVWmM/view?usp=sharing&resourcekey=0-Qt1z5FXgNSZ9RZZ5vaISbQ",
    links: [
      "https://drive.google.com/file/d/0By856O3q58sGbmtMc2l5NGpUOFE/view?usp=sharing&resourcekey=0-qJh9Vvqc5tX88LS-3nVSYA",
    ],
    key: "https://drive.google.com/file/d/0By856O3q58sGOFBKOGVITXVCakE/view?usp=sharing&resourcekey=0-SJu3xP3bdgnDc0n7ivK-2A",
    notes: "missing stations; stations key in additional links",
  },
  {
    type: "test",
    event: "Experimental Design",
    year: "2014-2015",
    tournament: "Westlake Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGek00VFlzNmdLeWs/view?usp=sharing&resourcekey=0-1nxmv4QKG-9UcboNiHe_sw",
    key: "https://drive.google.com/file/d/0By856O3q58sGRWduUWNHamgxYW8/view?usp=sharing&resourcekey=0-Pn9xEmioeq-XZQr4SmgM2w",
  },
  {
    type: "test",
    event: "Entomology",
    year: "2014-2015",
    tournament: "Westlake Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGSURDRHJIUUhoVmc/view?usp=sharing&resourcekey=0-r3swz17Bg4QFztHp1eoFgA",
    key: "https://drive.google.com/file/d/0By856O3q58sGNE0tbVgzT3dMaXM/view?usp=sharing&resourcekey=0-8Xjm1sq6dzkeOhUDFeGwWQ",
  },
  {
    type: "test",
    event: "Dynamic Planet",
    year: "2014-2015",
    tournament: "Westlake Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGSHNqaHJpWlJmakk/view?usp=sharing&resourcekey=0-zVr5FHIKBglJIST-CbaW6g",
    key: "https://drive.google.com/file/d/0By856O3q58sGUXFFcjJYc0x0eHc/view?usp=sharing&resourcekey=0-41uHpF7bTeymo-a2_QldpA",
  },
  {
    type: "test",
    event: "Disease Detectives",
    year: "2014-2015",
    tournament: "Westlake Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGZFEzd1dIa29iZWs/view?usp=sharing&resourcekey=0-uksTHOckGNytBCGHNQnmrA",
    key: "https://drive.google.com/file/d/0By856O3q58sGYzUyNkNZemZ3YWs/view?usp=sharing&resourcekey=0-wNuUUQFKUAlmsogIrJ_0Gw",
  },
  {
    type: "test",
    event: "Compound Machines",
    year: "2014-2015",
    tournament: "Westlake Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGZk9ac1ctLTYxUlE/view?usp=sharing&resourcekey=0-k3W07kEwjz9G8iXp1nG-DA",
    key: "https://drive.google.com/file/d/0By856O3q58sGSEFMRzJUNHZhN1U/view?usp=sharing&resourcekey=0-uBR6f5c3nBVyB-TbS5L9iQ",
  },
  {
    type: "test",
    event: "Chemistry Lab",
    year: "2014-2015",
    tournament: "Westlake Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGaEE2bXIwODB3T0E/view?usp=sharing&resourcekey=0-CDtn4LCT9dGHL4ronwLJaw",
    key: "https://drive.google.com/file/d/0By856O3q58sGYTd3LW91QmlqbG8/view?usp=sharing&resourcekey=0-zhrGlWpJafmu-iUe6uD-rw",
  },
  {
    type: "test",
    event: "Cell Biology",
    year: "2014-2015",
    tournament: "Westlake Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGaE5qRVV1Y0Z1MEU/view?usp=sharing&resourcekey=0-Bhg76jFc_9IGQIpkwaSz_g",
    key: "https://drive.google.com/file/d/0By856O3q58sGT3ZtQnl3RHJnRmM/view?usp=sharing&resourcekey=0-R6xEWSpKPnrsv4b4baCXkQ",
  },
  {
    type: "test",
    event: "Astronomy",
    year: "2014-2015",
    tournament: "Westlake Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGMk1PU2xQdkxZXzg/view?usp=sharing&resourcekey=0-UI93xF0Y_Oq0j2HzgKk_wg",
    links: [
      "https://drive.google.com/file/d/0By856O3q58sGbkNnSDdTQ2ppMEU/view?usp=sharing&resourcekey=0-ql0w5Zo_1NWcBs4dn5_P-w",
    ],
    key: "https://drive.google.com/file/d/0By856O3q58sGRXVHMHVwM1BRZE0/view?usp=sharing&resourcekey=0-T-ry7sa9FbLOqQvr7vZIOQ",
    notes: "images in additional links",
  },
  {
    type: "test",
    event: "Anatomy and Physiology",
    year: "2014-2015",
    tournament: "Westlake Invite",
    link: "https://drive.google.com/file/d/0By856O3q58sGaWZHOEJqNGFHV2s/view?usp=sharing&resourcekey=0-pxorWeunCTevNAsEu5RCOg",
    key: "https://drive.google.com/file/d/0By856O3q58sGMm51YzBZY3RmYWs/view?usp=sharing&resourcekey=0-dq9VJngbAgBWaIquX6Xv2g",
  },

  {
    type: "test",
    event: "Astronomy",
    year: "2023-2024",
    tournament: "Mason Invite",
    link: "https://drive.google.com/file/d/1XkgOceeRxnl9Fo8WfAHPbtinA_X2T-J3/view",
    key: "https://drive.google.com/file/d/1B6Vqh1L1wA2DX7czOB1pgdxeptNKOCCf/view",
  },
  {
    type: "test",
    event: "Anatomy and Physiology",
    year: "2023-2024",
    tournament: "Mason Invite",
    link: "https://drive.google.com/file/d/1A6nqJThGcYtpxyF3wISC88bF6vDaHrDW/view",
    key: "https://drive.google.com/file/d/1m8xLkucVHcKkQeHxflsRJysrhXaxc3FK/view",
  },
  {
    type: "test",
    event: "Chemistry Lab",
    year: "2023-2024",
    tournament: "Mason Invite",
    link: "https://drive.google.com/file/d/1XDEayn_YmS0x3N4cAWFsXdjdo4tgFUwl/view",
    key: "https://drive.google.com/file/d/1cVtS-dOGwoO4f59gYLfe_gGIdoWPejbA/view",
  },
  {
    type: "test",
    event: "Codebusters",
    year: "2023-2024",
    tournament: "Mason Invite",
    link: "https://drive.google.com/file/d/1ezPEFdklQl2Qam5bypgvC7KV163K3c3w/view",
    key: "https://drive.google.com/file/d/13N7IvKq2NqscmLrdFYw8Kp-PH7dVx4-a/view",
  },
  {
    type: "test",
    event: "Detector Building",
    year: "2023-2024",
    tournament: "Mason Invite",
    link: "https://drive.google.com/file/d/1y7UHKIfRh1yjuF8KRht1MdEGzkfbKQhs/view",
    key: "https://drive.google.com/file/d/1wQLz8InbHEGWBfQaxO4ApZw_X-cYfWqn/view",
  },
  {
    type: "test",
    event: "Disease Detectives",
    year: "2023-2024",
    tournament: "Mason Invite",
    link: "https://drive.google.com/file/d/1c7z-o1qzsGtsC5aTW_mnG-bZH_XD3FH5/view",
    key: "https://drive.google.com/file/d/1Q6NY9bEThHp3anQwuJqkTojwCWJ7L1G0/view",
  },
  {
    type: "test",
    event: "Dynamic Planet",
    year: "2023-2024",
    tournament: "Mason Invite",
    link: "https://drive.google.com/file/d/1tzSNasRgk4jkg04rV4LG2QQnwKLuAv0s/view",
    key: "https://drive.google.com/file/d/1XQ1az1jbLuq1YggpGHLvEe7iTBOkmiyE/view",
  },
  {
    type: "test",
    event: "Ecology",
    year: "2023-2024",
    tournament: "Mason Invite",
    link: "https://drive.google.com/file/d/1SSsIxmPRbF_XrGpgXK5i-QFzv52NAkwh/view",
    key: "https://drive.google.com/file/d/1VkKK2u5N4yWlIhH8Vj9gc40B456Bht1N/view",
  },
  {
    type: "test",
    event: "Experimental Design",
    year: "2023-2024",
    tournament: "Mason Invite",
    link: "https://drive.google.com/file/d/1mjmRxFV7hkKFoklm1BXPu0KGWkoZWIcL/view?usp=share_link",
    notes: "No key",
  },
  {
    type: "test",
    event: "Fermi Questions",
    year: "2023-2024",
    tournament: "Mason Invite",
    link: "https://drive.google.com/file/d/1mlisZEzK_3A8KmlipofDyRavYMcnt1Hs/view",
    key: "https://drive.google.com/file/d/17o_E3dwv8Obp3nzqPJ0sx6fTc505UBuv/view",
  },
  {
    type: "test",
    event: "Forensics",
    year: "2023-2024",
    tournament: "Mason Invite",
    link: "https://drive.google.com/file/d/1u7Che4RAyOgPi7_BUS0xquXHdYsgf-kC/view",
    key: "https://drive.google.com/file/d/1PqIGRojEhMqOPobKTswQ5GA-lIbugZ6u/view",
  },
  {
    type: "test",
    event: "Forestry",
    year: "2023-2024",
    tournament: "Mason Invite",
    link: "https://drive.google.com/file/d/1Bcim2Bn7BQ_FOgQjS0V0Zdi-tySuJVpx/view",
    key: "https://drive.google.com/file/d/1zXSNw49VEA4stkPusxKLAFbOfJZ4e7Gq/view",
    links: [
      "https://drive.google.com/file/d/1h0I0Ge_tPwLhZVsB9bQJjPP55c4EJoBl/view?usp=share_link",
    ],
    notes: "answer sheet below",
  },
  {
    type: "test",
    event: "Fossils",
    year: "2023-2024",
    tournament: "Mason Invite",
    link: "https://drive.google.com/file/d/1cwEitiqD7CGIxUa9ZaLqhasbJTSFkzJA/view",
    key: "https://drive.google.com/file/d/10ykPA8823e0lckXTwzc4x1ac0h46dpfs/view",
    links: [
      "https://drive.google.com/file/d/1PHOu6tYBvGVQMjvsPvXpfLKeuKEoZXau/view",
    ],
    notes: "answer sheet below",
  },
  {
    type: "test",
    event: "Geologic Mapping",
    year: "2023-2024",
    tournament: "Mason Invite",
    link: "https://drive.google.com/file/d/1brsRvqLm8beJG3iHDQMBEGVDDLFNFkgJ/view",
    key: "https://drive.google.com/file/d/1Blj3S326rK-aaS9MxPv-I8M99SDEsn3m/view",
  },
  {
    type: "test",
    event: "Microbe Mission",
    year: "2023-2024",
    tournament: "Mason Invite",
    link: "https://drive.google.com/file/d/1VAIe4VEDTUmv2ucGfFsEhvSmuONJ6uZi/view",
    key: "https://drive.google.com/file/d/1UDD2m50m6Ds1znWM1S0fO5mUMDUkHeWV/view",
  },
  {
    type: "test",
    event: "Optics",
    year: "2023-2024",
    tournament: "Mason Invite",
    link: "https://drive.google.com/file/d/1rBlNQTZG2c9-LSEmEWhoJA7SBNEUEoiL/view",
    key: "https://drive.google.com/file/d/1c3wt5ui5FlTuEstkeoL_kLwvldiMZDnq/view",
  },
  {
    type: "test",
    event: "Wind Power",
    year: "2023-2024",
    tournament: "Mason Invite",
    link: "https://drive.google.com/file/d/1NSCievoIPJTiib0Nk4r50o6VUVj8YZrz/view",
    key: "https://drive.google.com/file/d/1VUrK1WYO_m45HvGNT12JiZC7kw5eyKO1/view",
  },
  {
    type: "test",
    event: "Write It Do It",
    year: "2023-2024",
    tournament: "Mason Invite",
    links: [
      "https://drive.google.com/file/d/1lxMum6IcdBtFr69octvjai1ALtk8kRP3/view",
      "https://drive.google.com/file/d/1miXUUc8bjXM1QiORryJhlOEny4jQbN-P/view",
      "https://drive.google.com/file/d/1mvWlg54X2ybpU6rDGhWrW1STVDDL3CUc/view",
      "https://drive.google.com/file/d/1mkrkz5RwzJqwpgawleo0dulZRuOZ4in0/view",
      "https://drive.google.com/file/d/1mrAnUIZBoLcqigdi2UfJrDDK7KbbQJRJ/view",
    ],
  },
  {
    type: "test",
    event: "Write It Do It",
    year: "2023-2024",
    tournament: "Rickards",
    link: "https://drive.google.com/file/d/1RDNc6bhEBTWZiD_GxxU5iK47lHgAwbCw/view?usp=drive_link",
    key: "https://drive.google.com/file/d/1NYNca2SjFqQoMyXoWxQGTUrRDlz76vaJ/view?usp=drive_link",
  },

  {
    type: "test",
    event: "Ornithology",
    year: "2023-2024",
    tournament: "Rickards",
    link: "https://docs.google.com/document/d/1SmH2B6Q_8Ix3TRuXs45xRuSUFkSsTceEFKk8OFm6yow/edit?usp=drive_link",
    key: "https://docs.google.com/document/d/17MILxWnvwjnqZ2eZzuVOBZ9bg972buIWeFEEtLZCaRc/edit?usp=drive_link",
  },

  {
    type: "test",
    event: "Lean Mean Meme Machine",
    year: "2023-2024",
    tournament: "Rickards",
    link: "https://drive.google.com/file/d/1M2RvuXo8Ijw0Z-EX2suFpjtGR0ODciAE/view?usp=drive_link",
    key: "https://drive.google.com/file/d/1fuyH9lJj7tjTzqUleV2XhhVKIT_nz58l/view?usp=drive_link",
  },

  {
    type: "test",
    event: "Fossils",
    year: "2023-2024",
    tournament: "Rickards",
    link: "https://drive.google.com/file/d/13iKtJ3_jmAkkUyptRXK0RO_28XYW_uIx/view?usp=drive_link",
    key: "https://drive.google.com/file/d/1xU7wKqtOazXd41Gzfm_15ldOrIWeytax/view?usp=drive_link",
  },

  {
    type: "test",
    event: "Fermi Questions",
    year: "2023-2024",
    tournament: "Rickards",
    link: "https://drive.google.com/file/d/1kNlQ58-K6g4LgCrWbafmiDcrULqrXASc/view?usp=drive_link",
    key: "https://drive.google.com/file/d/1D3yb9xxyLr5nBiLugXu_fgQqsZx-iXAw/view?usp=drive_link",
  },

  {
    type: "test",
    event: "Dynamic Planet",
    year: "2023-2024",
    tournament: "Rickards",
    link: "https://drive.google.com/file/d/1pdeaoN3y-BRjQtCaiadWsM2xhdCjXTuZ/view?usp=drive_link",
    key: "https://drive.google.com/file/d/1tVWoHL85rRywy8oXgQjj51H_gEnXgKOk/view?usp=drive_link",
  },

  {
    type: "test",
    event: "Codebusters",
    year: "2023-2024",
    tournament: "Rickards",
    link: "https://drive.google.com/file/d/1KUokVWVOKlhQjRXigrT6tEq52nXGxS4C/view?usp=drive_link",
    key: "https://drive.google.com/file/d/1CwB-Q3x7CeQ7NqFmiPTEeQldm5crdCTe/view?usp=drive_link",
  },

  {
    type: "test",
    event: "Anatomy and Physiology",
    year: "2023-2024",
    tournament: "Rickards",
    link: "https://docs.google.com/document/d/1FioiIX6LtYmKK-yU6030dXpJnQlmaGtVuK2hg2uNMLY/edit?usp=drive_link",
    key: "https://docs.google.com/document/d/1Y1Qk7i2BCOWuRqBdHz9TQfWJF5i9GR-OhHqaHuo4fN8/edit?usp=drive_link",
  },

  {
    type: "test",
    event: "Wind Power",
    year: "2023-2024",
    tournament: "Rickards",
    link: "https://docs.google.com/document/d/1_8AgqOuP-6kx2CPAz8K9-u7QAq1HUzfqrYKpWjcfCTE/edit?usp=drive_link",
    key: "https://docs.google.com/document/d/1h-sb05OjSzp_eaWBE11guREn6y4DSloAjbuhK4kK3c0/edit?usp=drive_link",
  },

  {
    type: "test",
    event: "Optics",
    year: "2023-2024",
    tournament: "Rickards",
    link: "https://drive.google.com/file/d/1nAWxzt3Aw52vfu5BJgXuA0hjA4HuPcsp/view?usp=drive_link",
    key: "https://drive.google.com/file/d/1ZSvhhcgTLWCvNoNjyLLDyRspsfGNT6hG/view?usp=drive_link",
  },

  {
    type: "test",
    event: "Geologic Mapping",
    year: "2023-2024",
    tournament: "Rickards",
    link: "https://docs.google.com/document/d/1edwW7A2Q1qbh2Af7UD_10_z9XJi7iDuzEq0EvvfRFm4/edit?usp=drive_link",
    key: "https://docs.google.com/document/d/1ZS9_eh_ExnukAfqY02LciL3Gj9fT3QEuVasyQwWWntY/edit?usp=drive_link",
  },

  {
    type: "test",
    event: "Forestry",
    year: "2023-2024",
    tournament: "Rickards",
    link: "https://docs.google.com/document/d/1VLrIthaCi-ig_wp0bBxRKvv8pId0QgeinAbiIsSKwgA/edit?usp=drive_link",
    key: "https://docs.google.com/document/d/13CKTgbat0i_MYKRD43kb4U8vdr2ktKwJly7eqnnr0jQ/edit?usp=drive_link",
  },

  {
    type: "test",
    event: "Experimental Design",
    year: "2023-2024",
    tournament: "Rickards",
    link: "https://docs.google.com/document/d/1lgrWCwfDcuL-Wn0e8EVCpBTkLsYRAedspwQ5RK1Nb9Y/edit?usp=drive_link",
    notes: "no key",
  },

  {
    type: "test",
    event: "Disease Detectives",
    year: "2023-2024",
    tournament: "Rickards",
    link: "https://drive.google.com/file/d/1nkSA2Mr4VFntEzsBd69-OGNiK14WlTf3/view?usp=drive_link",
    key: "https://drive.google.com/file/d/1inxj259wL0PO2r3nLdzwDepgy-IaY7mu/view?usp=drive_link",
  },

  {
    type: "test",
    event: "Chemistry Lab",
    year: "2023-2024",
    tournament: "Rickards",
    link: "https://docs.google.com/document/d/1Yk4isC59YZZi6t0DTU_OVShp6wNrsQmXojpRtFM4N3U/edit?usp=drive_link",
    key: "https://docs.google.com/document/d/1FfeEMZWuidDf2CmVI-7RXzHBnoERsARsxsuvW_y1fyg/edit?usp=drive_link",
  },

  {
    type: "test",
    event: "Anagrams",
    year: "2023-2024",
    tournament: "Rickards",
    link: "https://docs.google.com/document/d/1euSr6Hf8SwLZeb725ZFEmFx3zRq7wCA3oDU6eKaYgOI/edit?usp=drive_link",
  },

  {
    type: "test",
    event: "We've Got Your Number",
    year: "2023-2024",
    tournament: "Rickards",
    link: "https://docs.google.com/document/d/1cTyhAZ8BHWWEEocJmDn_oX7UcZnjiTObLEuQOmTHOYI/edit?usp=drive_link",
  },

  {
    type: "test",
    event: "Microbe Mission",
    year: "2023-2024",
    tournament: "Rickards",
    link: "https://docs.google.com/document/d/1_RALHyXRpE6jP36w08kWWyN4xfY4_-0776C2RFEv3es/edit?usp=drive_link",
    key: "https://docs.google.com/document/d/18pa9eyhyMAfI6XoANRSnRbxFtihjtitj1aXUfumff5c/edit?usp=drive_link",
  },

  {
    type: "test",
    event: "Geoguessr",
    year: "2023-2024",
    tournament: "Rickards",
    link: "https://docs.google.com/document/d/1L_Jq_oPWpvU7ERiEw1yrAX0XT9tFzIC3Wx2BoKOjMxY/edit?usp=drive_link",
    key: "https://docs.google.com/document/d/1SPOUpz4i7wsfxCkTiv2mXES5WoZ-mlSLmIEj0_Tbu3Y/edit?usp=drive_link",
  },

  {
    type: "test",
    event: "Forensics",
    year: "2023-2024",
    tournament: "Rickards",
    link: "https://drive.google.com/file/d/1vZmoUOeCaXyW818jnUHUZstmucU8oAYP/view?usp=drive_link",
    key: "https://drive.google.com/file/d/1IRKsYQ5b14Fivg4jxmriBNaKsXwifl23/view?usp=drive_link",
  },

  {
    type: "test",
    event: "Ecology",
    year: "2023-2024",
    tournament: "Rickards",
    link: "https://docs.google.com/document/d/1yCC5yj-Sh7hdn7H8pF691o2EvukAnv1vYo6Teqbf0DU/edit?usp=drive_link",
    key: "https://docs.google.com/document/d/13eC4KqihztYVaX8UsCyzO5YbhgRaTcno3qNJ0mFJ7K0/edit?usp=drive_link",
  },

  {
    type: "test",
    event: "Detector Building",
    year: "2023-2024",
    tournament: "Rickards",
    link: "https://drive.google.com/file/d/176DxPYAfK5YhB3SXstO1i_gFmRn6Lmk5/view?usp=drive_link",
    key: "https://drive.google.com/file/d/1esdGQmbKwT6TllKsa2pcp0FdteVfvJ5X/view?usp=drive_link",
  },

  {
    type: "test",
    event: "Astronomy",
    year: "2023-2024",
    tournament: "Rickards",
    link: "https://drive.google.com/file/d/1s6kPexO4Eni3qlXEVENNrLgMfTQZNwWS/view?usp=drive_link",
    links: [
      "https://drive.google.com/file/d/1yqxPMVk5LXhG3GWTDsUGlA4iEN5ERWAE/view?usp=drive_link",
      "https://drive.google.com/file/d/1ossKFpR-_jlbvXAJj90OQvBUW_AMbZqN/view?usp=drive_link",
    ],
    key: "https://drive.google.com/file/d/1h2uFXuLEYwp2k0o4JgfkYRYMEIS30QM2/view?usp=drive_link",
    notes: "Image Sheet and Calculation and JS9 solution in additional links",
  },

  {
    type: "test",
    event: "Wind Power",
    year: "2023-2024",
    tournament: "Mason Tryouts",
    link: "https://drive.google.com/file/d/1bz9hk-xTm9tAVw5EleZu5WTOJW1P0wro/view?usp=drive_link",

    key: "https://drive.google.com/file/d/1ys_OOOWvu22Q891GN3iaAVn6rmiobJZl/view?usp=drive_link",
  },

  {
    type: "test",
    event: "Fossils",
    year: "2023-2024",
    tournament: "Mason Tryouts",
    link: "https://drive.google.com/file/d/1XrKpusxx5tF3GHk-uOTWFt0DTw7h32hu/view?usp=drive_link",
    key: "https://drive.google.com/file/d/1J7R2fXSDlDEUTT5vAxuL6Q-G088XU54x/view?usp=drive_link",
  },

  {
    type: "test",
    event: "Dynamic Planet",
    year: "2023-2024",
    tournament: "Mason Tryouts",
    link: "https://drive.google.com/file/d/1laiWuDCibsXkx1rZdS5rw2YqEL-RQx1Y/view?usp=drive_link",
    key: "https://drive.google.com/file/d/1M35oEgx441eRQE_P22azkPcJjOUXFaGT/view?usp=drive_link",
  },

  {
    type: "test",
    event: "Chemistry Lab",
    year: "2023-2024",
    tournament: "Mason Tryouts",
    link: "https://drive.google.com/file/d/1di6siILw2r-nifIv00uBJKmNdqRQ0RRw/view?usp=drive_link",
    key: "https://drive.google.com/file/d/1s1rODvY1LVUxUF6ForgVZTDv4yNC7ZEh/view?usp=drive_link",
  },

  {
    type: "test",
    event: "Microbe Mission",
    year: "2023-2024",
    tournament: "Mason Tryouts",
    link: "https://drive.google.com/file/d/1M4MLG_RgDypQQQBGpl5-N4knjvmZgra1/view?usp=drive_link",
    key: "https://drive.google.com/file/d/1zadr06Ub_4er1V7mUzFXhLVw2aK7ONLf/view?usp=drive_link",
  },

  {
    type: "test",
    event: "Forestry",
    year: "2023-2024",
    tournament: "Mason Tryouts",
    link: "https://drive.google.com/file/d/1uZuYqOEXPg8kz-SvnGBMHDbLf_qMiiOK/view?usp=drive_link",
    key: "https://drive.google.com/file/d/12qU0JAuUA6OmSrIL1tUEaY0yLfjoy5Mm/view?usp=drive_link",
  },

  {
    type: "test",
    event: "Disease Detectives",
    year: "2023-2024",
    tournament: "Mason Tryouts",
    link: "https://drive.google.com/file/d/14khn3nu633H6Il4WRAZvFOG2xkK4pgpO/view?usp=drive_link",
    key: "https://drive.google.com/file/d/1OA4_LonbIDSG5Ue3vbIkv3O3mV09eCBa/view?usp=drive_link",
  },

  {
    type: "test",
    event: "Astronomy",
    year: "2023-2024",
    tournament: "Mason Tryouts",
    link: "https://drive.google.com/file/d/1rS79KgAjlKsjn_XddLjOAMRQuDmsPYCT/view?usp=drive_link",

    key: "https://drive.google.com/file/d/1hor0bxmmNCvezwynWLiUypA3IpZqIJFQ/view?usp=drive_link",
  },

  {
    type: "test",
    event: "Geologic Mapping",
    year: "2023-2024",
    tournament: "Mason Tryouts",
    link: "https://drive.google.com/file/d/1Rci-ISwhV-aHu9IfCss360LKyprVhZo2/view?usp=drive_link",

    key: "https://drive.google.com/file/d/1Xc93fZ73PeskBjh3vJ_ZsKwflj1UBP3-/view?usp=drive_link",
  },

  {
    type: "test",
    event: "Fermi Questions",
    year: "2023-2024",
    tournament: "Mason Tryouts",
    link: "https://drive.google.com/file/d/1D4LUdtuOrjmiP3VbsqZkzMk2unFzQFwu/view?usp=drive_link",

    key: "https://drive.google.com/file/d/1fLJlfDsfAMI8ZaJR9IHLSVa0ZrUyEHnS/view?usp=drive_link",
  },

  {
    type: "test",
    event: "Codebusters",
    year: "2023-2024",
    tournament: "Mason Tryouts",
    link: "https://drive.google.com/file/d/1gFknRz-DmY-Jhtu7qOi0XKUQu1qAh0ZF/view?usp=drive_link",

    key: "https://drive.google.com/file/d/12Oyxyg6-ufhFjgxvEIG6cwLu53Ixmk6y/view?usp=drive_link",
  },

  {
    type: "test",
    event: "Anatomy and Physiology",
    year: "2023-2024",
    tournament: "Mason Tryouts",
    link: "https://drive.google.com/file/d/1Dc6Eud2Wmb8X_H8i58caxv9sjdJJY39J/view?usp=drive_link",
    key: "https://drive.google.com/file/d/1LZnxr4QHqOlrXLuk8NFIEfGJ8QQ-YCxP/view?usp=drive_link",
  },
].map((e) => {
  return { ...e, internal_name: e.event.toLowerCase().replace(/\W/g, "") };
});
